before_install: 
  - "eval \"${MATRIX_EVAL}\""
language: cpp
matrix: 
  include: 
    - 
      before_install: 
        - "sudo apt-get update"
        - "sudo apt-get install -y g++ make libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev"
      env: 
        - "MATRIX_EVAL=\"CC=gcc && CXX=g++\""
      os: linux
      script: 
        - make
